apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z44ir71uq-go
  janus-idp.io/tekton: z44ir71uq-go
  backstage.io/kubernetes-id: z44ir71uq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z44ir71uq-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
